# Generated by Django 4.2.5 on 2023-11-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=50)),
                ('telefono', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=50)),
                ('producto', models.CharField(max_length=50)),
                ('numero_de_boleta', models.CharField(max_length=10)),
                ('medio_de_compra', models.CharField(max_length=15)),
                ('cambio_o_devolucion', models.CharField(max_length=15)),
                ('comentarios', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='motocicletas',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
