# Generated by Django 4.2.5 on 2023-12-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionWeb', '0002_contacto_alter_motocicletas_precio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
